num1 = input("Enter your first number: ")
num2 = input("Enter your second number: ")
print(num1 + num2)
# print(num1 - num2)
# print(num1 / num2)
# print(num1 // num2)    
# print(num1 % num2)
# print(num1 ** num2)

print("The addition of two numbers are:",int(num1) + int(num2))
print("The subtraction of two numbers are:",int(num1) - int(num2))
print("The Division of two numbers are:",int(num1) / int(num2))
print("The floor Division of two numbers are:",int(num1) // int(num2))
print("The Modules of two numbers are:",int(num1) % int(num2))
print("The Exponential of two numbers are:",int(num1) ** int(num2))

Num1 = int(input("Enter your first favorite number: "))
Num2 = int(input("Enter your second favorite number: "))

print(Num1 + Num2)
print(Num1 - Num2)
print(Num1 * Num2)
print(Num1 / Num2)
print(Num1 // Num2)
print(Num1 % Num2)
print(Num1 ** Num2)
